- helm-chart/splunk-connect-for-kubernetes/README.md
> Update README.md, fixes #8

- helm-chart/splunk-connect-for-kubernetes/requirements.yaml
- helm-chart/splunk-connect-for-kubernetes/templates/NOTES.txt
- helm-chart/splunk-connect-for-kubernetes/values.yaml
All subcharts are now optional, and we are following
https://docs.helm.sh/chart_best_practices/#conditions-and-tags
> Make dependency charts optional, fixes #26

- .circleci/config.yml
- .circleci/deploy_connector.sh
- .circleci/run_functional_tests.sh
- test/README.md
- test/common.py
- test/conftest.py
- test/k8s_logging_tests/test_index.py
- test/requirements.txt
Added fuctional tests setup (pytests framework)  and added a basic test for k8s-logging. Also added deployment teardown step.
> Added fuctional tests setup (pytests framework) 

- helm-chart/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml
updated metrics-aggr configmap to make indexName configurable.
> updated aggr configmap to make indexName configurable

- .circleci/deploy_connector.sh
Check and teardown previous k8s deployment.
> Check and teardown k8s deployment 

- LICENSE
- README.md
- helm-chart/splunk-connect-for-kubernetes/OWNERS
- helm-chart/splunk-connect-for-kubernetes/README.md
- helm-chart/splunk-connect-for-kubernetes/templates/NOTES.txt
- helm-chart/splunk-kubernetes-logging/OWNERS
- helm-chart/splunk-kubernetes-logging/README.md
- helm-chart/splunk-kubernetes-metrics/OWNERS
- helm-chart/splunk-kubernetes-metrics/README.md
- helm-chart/splunk-kubernetes-objects/OWNERS
- helm-chart/splunk-kubernetes-objects/README.md
> Update all references from v1.0.1 to v1.1.0, doc updates, chart

- helm-chart/splunk-connect-for-kubernetes/Chart.yaml
- helm-chart/splunk-kubernetes-logging/Chart.yaml
- helm-chart/splunk-kubernetes-metrics/Chart.yaml
- helm-chart/splunk-kubernetes-objects/Chart.yaml
Pull request from community contributor - https://github.com/splunk/splunk-connect-for-kubernetes/pull/123
> Add appVersion to Charts

- helm-chart/splunk-kubernetes-logging/templates/_helpers.tpl
- helm-chart/splunk-kubernetes-logging/templates/daemonset.yaml
- helm-chart/splunk-kubernetes-logging/values.yaml
Merging https://github.com/splunk/splunk-connect-for-kubernetes/pull/49 against develop
> Merge community PR for variable docker logs path

- helm-chart/splunk-kubernetes-logging/templates/daemonset.yaml
- helm-chart/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml
- helm-chart/splunk-kubernetes-objects/templates/deployment.yaml
- manifests/splunk-kubernetes-logging/daemonset.yaml
extensions/v1beta1 will be deprecated in 1.16. See release notes - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#deprecations-and-removals
> extensions/v1beta1 -> apps/v1

- helm-chart/splunk-kubernetes-logging/templates/configMap.yaml
Fixed problem resolving source on line 212 of configMap for splunk-kubernetes-logging.
A bug was submitted previously, and can be found here: #217
Sorry for the incorrect fix earlier.
- [x ] Bugfix (non-breaking change which fixes an issue)
- [x ] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x ] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
> Fixed problem in splunk-kubernetes-logging configMap. #217

- helm-chart/splunk-kubernetes-logging/templates/configMap.yaml
> updated configuration for systemd plugin to use matches as filters is deprecated

- helm-chart/splunk-kubernetes-logging/examples/mini_custom_metadata.yaml
- helm-chart/splunk-kubernetes-logging/templates/_helpers.tpl
- helm-chart/splunk-kubernetes-logging/templates/configMap.yaml
- helm-chart/splunk-kubernetes-logging/values.yaml
- helm-chart/splunk-kubernetes-objects/templates/configMap.yaml
- helm-chart/splunk-kubernetes-objects/values.yaml
> added indexed fields to logging and objects

- README.md
- fields.conf.example
Added documentation and example file for #196
> updated docs to talk about metadata

- .circleci/config.yml
no need to install python. it comes installed## Types of changes
> reduce machine prep time

- .circleci/config.yml
- .circleci/performance/run_perf_scenarios.py
- .circleci/sck_values.yml
- .circleci/update_sck_config_perf.sh
- .gitignore
- README.md
- helm-chart/splunk-kubernetes-logging/templates/_helpers.tpl
- helm-chart/splunk-kubernetes-logging/templates/clusterRole.yaml
- helm-chart/splunk-kubernetes-logging/templates/clusterRoleBinding.yaml
- helm-chart/splunk-kubernetes-logging/templates/configMap.yaml
- helm-chart/splunk-kubernetes-logging/templates/daemonset.yaml
- helm-chart/splunk-kubernetes-logging/templates/serviceAccount.yaml
- helm-chart/splunk-kubernetes-logging/values.yaml
- test/common.py
- test/conftest.py
- test/k8s_logging_tests/test_config_logging.py
- test/test_setup.yaml
collecting pod labels and annotations && namespace annotation based routing
> collecting labels annotations && namespace annotation routing

- README.md
- helm-chart/splunk-connect-for-kubernetes/README.md
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/README.md
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/README.md
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/README.md
Fix readme installation instructions
> Update all readme.md to last version

- README.md
- helm-chart/splunk-connect-for-kubernetes/README.md
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/README.md
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/README.md
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/README.md
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml
- helm-chart/splunk-connect-for-kubernetes/values.yaml
> merge develop to master

- .circleci/config.yml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml
- manifests/splunk-kubernetes-logging/configMap.yaml
* update splunk version to 8.0.3 for test
* Fixes:
https://github.com/splunk/splunk-connect-for-kubernetes/issues/358
https://github.com/splunk/splunk-connect-for-kubernetes/issues/351
Includes suggested changes from these PR:
https://github.com/splunk/splunk-connect-for-kubernetes/pull/367
https://github.com/splunk/splunk-connect-for-kubernetes/pull/352
> Concat control

- helm-chart/splunk-connect-for-kubernetes/values.yaml
https://github.com/splunk/splunk-connect-for-kubernetes/issues/360
> Update indexed felds link

- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml
- helm-chart/splunk-connect-for-kubernetes/values.yaml
This PR addresses https://github.com/splunk/splunk-connect-for-kubernetes/issues/384
> Add port for kubelet aggregator

- helm-chart/splunk-connect-for-kubernetes/README.md
- [ x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x ] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [ x] I have added necessary documentation (if appropriate)
- just a doc fix all bottom 4 urls - now = 404s.
I filed #329 PR earlier and it seems broken again.
https://github.com/splunk/splunk-connect-for-kubernetes/pull/329/commits/587bfcb3a …
> fixed 404s for 3 values.yaml and License links at bottom

- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml
- helm-chart/splunk-connect-for-kubernetes/values.yaml
Makes monitoring_agent in fluentd config is optional
> Makes monitoring agent is optional

- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml
- helm-chart/splunk-connect-for-kubernetes/values.yaml
Fix typo in values description (`insecureSSL`, `openshift`)
> Fix typo in values description

- helm-chart/splunk-connect-for-kubernetes/Chart.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/Chart.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/README.md
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml
- helm-chart/splunk-connect-for-kubernetes/requirements.yaml
- helm-chart/splunk-connect-for-kubernetes/values.yaml
Allow users to send the raw event to splunk. This solves: https://github.com/splunk/splunk-connect-for-kubernetes/issues/509
> allow keeping docker/journald logging structure

- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml
- helm-chart/splunk-connect-for-kubernetes/values.yaml
Changes for comments related to 'logFormat' value in 'values.yaml' 
- specify that it should be a time stamp (as per the code and examples?)
- better wording for examples (tbh the pharse 'you can' I interpreted at first as the examples that you can only use ;) )
- list the default value:
> 'values.yaml'  -  change comments for 'logFormat' setting

- helm-chart/splunk-connect-for-kubernetes/values.yaml
The variable is not used anywhere.
Probably replaced by `*.kubernetes.securityContext`.
> Remove unused openshift variable from values

- .circleci/config.yml
- .github/workflows/ci_build_test.yaml
- .gitignore
- ci_scripts/build_sck_artifacts.sh
- ci_scripts/deploy_connector.sh
- ci_scripts/k8s-splunk.yml
- ci_scripts/sck_values.yml
- lintconf.yaml
- test/conftest.py
- test/k8s_logging_tests/test_config_logging.py
- test/k8s_metrics_tests/test_config_metrics.py
- test/k8s_objects_tests/test_default_config_objects.py
> add ci pipeline for github actions

- helm-chart/splunk-connect-for-kubernetes/values.yaml
> comments for self singed certificate

- README.md
Created a topic about creating multiline filters, per the acceptance criteria in https://jira.splunk.com/browse/ADDON-22623
> Multiline filters 02 22 21

- helm-chart/splunk-connect-for-kubernetes/values.yaml
Documentation changes. Non-breaking.
This just corrects the spelling of some words in the `values.yaml` file.
> Spell Check in config values.yaml

- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
Reverts splunk/splunk-connect-for-kubernetes#682.
it has been addressed here splunk/fluent-plugin-splunk-hec#201
> Revert "Remove hec token from splunk logs"

- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMap.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml
Fixing https://github.com/splunk/splunk-connect-for-kubernetes/issues/381
> Updated sourcetype in metric and aggr plugin

- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
- test/k8s_logging_tests/test_config_logging.py
fixes https://github.com/splunk/splunk-connect-for-kubernetes/issues/709
> fixed issue  sourcetype was not applied to container logs

- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/README.md
Reverts splunk/splunk-connect-for-kubernetes#715
> Revert "Fix link"

- README.md
> Deleting leftovers from README

- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/_helpers.tpl
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/_helpers.tpl
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMap.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/_helpers.tpl
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml
- helm-chart/splunk-connect-for-kubernetes/values.yaml
Fixes https://github.com/splunk/splunk-connect-for-kubernetes/issues/708
> Updated default buffer settings and added consume_chunk_on_4xx_errors config

- helm-chart/splunk-connect-for-kubernetes/values.yaml
Fixes https://github.com/splunk/splunk-connect-for-kubernetes/issues/740
> fixed typo

- README.md
> correcting typo mistake

- README.md
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml
- helm-chart/splunk-connect-for-kubernetes/values.yaml
closes https://github.com/splunk/splunk-connect-for-kubernetes/issues/799
> added multiline separator config documentation

- test/common.py
- test/k8s_metrics_tests/test_metric_plugin.py
- test/pytest.ini
adding pytest.ini file,
adding some more logging for debugging purposes,
extending time for search query which is used to decide if we will skip stats metric tests
> tests improvements - more logging 

- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
- helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml
- helm-chart/splunk-connect-for-kubernetes/values.yaml
These changes allow to enable the propagation of namespace labels into pod logs.
> develop: Enable namespace labels propagation
