helm-chart/splunk-kubernetes-logging/examples/use_logs.yaml, helm-chart/splunk-kubernetes-logging/templates/_helpers.tpl, helm-chart/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-kubernetes-logging/values.yaml, manifests/splunk-kubernetes-logging/configMap.yaml
Logs being collected into splunk will have a new field called "cluster_name".
=> Adding an optional clusterName value in order to have the ability to filter by a cluster_name field in splunk.

helm-chart/splunk-kubernetes-metrics/templates/configMap.yaml, helm-chart/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml
* Add cluster_name and interval to metrics aggregator
* Add interval to metrics
Looks like this two configurations (cluster_name and interval) at source level were missing. First one cause metrics to send a `name` field with `cluster_name` (default) value, and the other to specify the interval in which data will be taken.
Also, I think it will also close #122
=> Add missing configurations to metrics & metrics aggregator

helm-chart/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml, helm-chart/splunk-kubernetes-metrics/values.yaml
added aggregatorTolerations variable to allow metrics aggregation tolerations to be set independently to the metrics pods.
For example, you may want the metrics collector daemonset to run on the master, however you probably don't want the aggregator to end up on a master node.
=> added aggregatorTolerations variable

Makefile, helm-chart/splunk-kubernetes-logging/templates/configMap.yaml, manifests/splunk-kubernetes-logging/configMap.yaml, manifests/splunk-kubernetes-metrics/configMap.yaml, manifests/splunk-kubernetes-metrics/configMapMetricsAggregator.yaml, manifests/splunk-kubernetes-metrics/deploymentMetricsAggregator.yaml
A path needs to be specified for where to save the pos file generated by
the fluentd plugin. You can find more information in the upgrade docs:
https://github.com/reevoo/fluent-plugin-systemd/blob/master/docs/upgrading.md
I ran `make manifests` and it generated some unrelated changes in the manifests. Are you trying to keep the manifests in sync with the makefile generated manifests?
=> Make systemd components persist a position file

helm-chart/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-kubernetes-logging/values.yaml
Added the possibility to change `path` and `exclude_path` to the fluentd configuration.
This will make it possible exclude noisy logs like networking services, tiller and even the fluentd log it self.
This is a solution on to my feature request issue:
https://github.com/splunk/splunk-connect-for-kubernetes/issues/152
=> Added support for path and exclude_path to be populated in fluentd configMap. Resolves issue #152

helm-chart/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-kubernetes-objects/templates/configMap.yaml
'host' fields in splunk logs are all empty. This pr to fix that by using the Kubernetes node name for the host field.
https://github.com/splunk/splunk-connect-for-kubernetes/issues/192
=> Fix host field with kubernetes node name

helm-chart/splunk-kubernetes-logging/templates/configMap.yaml
Fix for issue: https://github.com/splunk/splunk-connect-for-kubernetes/issues/194
This adds cluster_name metadata to journald and file sources also.
=> Add cluster-name for journald and file sources of logs

manifests/splunk-kubernetes-logging/daemonset.yaml, manifests/splunk-kubernetes-metrics/deployment.yaml, manifests/splunk-kubernetes-metrics/deploymentMetricsAggregator.yaml, manifests/splunk-kubernetes-objects/deployment.yaml
Add linux node selectors to deployments and daemonsets.  Prevents the pods from scheduling on windows nodes in a hybrid cluster.  
This is a necessary first step for https://github.com/splunk/splunk-connect-for-kubernetes/issues/163
=> Add linux node selector to deployments

helm-chart/splunk-kubernetes-logging/templates/configMap.yaml
Fixed problem with quotes not being correct on line 212 of configMap for splunk-kubernetes-logging. 
A bug was submitted previously, and can be found here: #208 
- [x ] Bugfix (non-breaking change which fixes an issue)
- [x ] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [x ] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
=> Fixed problem in splunk-kubernetes-logging configMap. #208

helm-chart/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-kubernetes-objects/values.yaml
=> Ensure clusterName can be used from global.kubernetes.clusterName

helm-chart/splunk-kubernetes-objects/templates/configMap.yaml
The PR #235 introduced a new if/else statement, but forgot to include an end clause.   
This resulted in a parsing error when trying to use the helm chart without index routing.
=> Missing end clause

helm-chart/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-kubernetes-objects/values.yaml, manifests/splunk-kubernetes-logging/daemonset.yaml, manifests/splunk-kubernetes-metrics/deployment.yaml, manifests/splunk-kubernetes-objects/deployment.yaml, tools/gen_manifest.rb
Selector labels are immutable after creation in apps/v1 as seen in the kubernetes [deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates
) and [daemonset](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#pod-selector) documentation. Using a version label in the selector blocks upgrades from proceeding via kubectl apply and requires deleting the resources before upgrading.
=> remove version label from selector in manifests

helm-chart/splunk-kubernetes-logging/templates/configMap.yaml
For multiline events, the events can be buffered and the last time stamp is used which can be several seconds off.  Setting **use_first_timestamp true** fixes this problem.
In Splunk my multiline events had extra newlines.  This was fixed by adding **separator ""**  This is because fluentd concat separator default is \n.
=> For multiline events, use the timestamp of the first event and do not add extra newlines

helm-chart/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-kubernetes-logging/templates/daemonset.yaml, helm-chart/splunk-kubernetes-logging/values.yaml, manifests/splunk-kubernetes-logging/configMap.yaml, manifests/splunk-kubernetes-logging/daemonset.yaml
This commit enables the [fluentd prometheus
plugin](https://github.com/fluent/fluent-plugin-prometheus) to expose
metrics on port 24231.
I'm proposing enabling the Prometheus fluentd plugin as it exposes some pretty important metrics (errors sending events using the splunk-hec plugin, etc). Being able to track these things is critical to using this in production.
=> Enable FluentD Prometheus Endpoint

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
This change add the ability to set refresh_interval and sets the default as 60s if not configured which is the fluentd default 
=> add refresh_interval to source.containers.conf (#389)

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceAccount.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/serviceAccount.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/deployment.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/serviceAccount.yaml
This merge is intended to fix the missing "imagePullSecret" issue occurring in the Helm chart deployments.
Before this fix, the only place having the correct "imagePullSecret" is at the deployment of "metric aggregation". All the rest Helm charts of deployments and daemonsets have "imagePullSecret" missing because the "imagePullSecret" in them are located in the ServiceAccount creation. If the SeviceAccount condition is not met, the "imagePullSecret" would not be included in the deployments, which may cause the deployment fails if the image is pulled through a Docker registry secret.
=> Feature image pull secrets

.circleci/sck_values.yml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/examples/mini_custom_metadata.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, test/k8s_logging_tests/test_config_logging.py, test/test_setup.yaml
I'd like to add an option to better customize fields in logging events by defining mappings between annotations that can be specified on a pod or namespace, and the corresponding field name it will be mapped to in Splunk.  This would allow for fairly flexible usage of annotations in kubernetes to enhance logging events with custom field values.
Issue: https://github.com/splunk/splunk-connect-for-kubernetes/issues/393
=> Add the ability to specify annotations for custom metadata fields

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/podSecurityPolicy.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/podSecurityPolicy.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/podSecurityPolicy.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
In some cases, AppArmor is not available, for example on CentOS nodes, therefore it should be possible to skip AppArmor annotations.
=> Optional disabling AppArmor annotations

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
By default fluentd uses ASCII-8BIT encoding internally by default
because it also could handle binary log types.
If you have 2-byte UTF-8 chars in your logs, you should enable
the option to set the encoding to UTF-8.
See issue #568
Based on the PR https://github.com/openshift/origin-aggregated-logging/pull/622
- [ x ] New feature (non-breaking change which adds functionality)
=> Option to encode strings as utf-8: charEncodingUtf8

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml
When setting `global.prometheus_enabled=true` the logging DaemonSet
doesn't include the metrics port. Only the annotations are added.
The Prometheus operator has PodMontor resources to define scraping
configuration. It's required to have named ports defined on the
container.
Example PodMonitor resource for splunk-kubernetes-logging:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
name: splunk-kubernetes-logging
spec:
selector:
matchLabels:
app: splunk-kubernetes-logging
podMetricsEndpoints:
- port: metrics
interval: 30s
```
There is a `targetPort` property too that would accept a
integer port. But it's marked as deprecated and also it didn't work
(invalid scraping config generated).
_Put an `x` in the boxes that …
=> Support PodMonitor resources for prometheus scraping

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, manifests/splunk-kubernetes-logging/configMap.yaml
A CRI log line can be P(partial) or F(ull). Currently the fluentd
config just throws away this information and logs partial lines
as distinct event to splunk.
This change should ensure that P lines are concatenated until
F line is reached. The same fluentd conact config is used within the
openshift integrated logging.
Closes #549 and #487
=> Concat partial CRI container file lines

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/clusterRoleBindingPrivilegedScc.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
On OpenShift ServiceAccounts that run privileged containers need
to have the privileged SCC ClusterRoleBinding.
Set `splunk-kubernetes-logging.rbac.openshiftPrivilegedSccBinding=true`
to manage this required resource on OpenShift.
=> Optionally manage the privileged SCC ClusterRoleBinding for OpenShift

README.md
It's already noted in the text of the helm deployment method, but
every YAML reader should be aware that it's not a supported
method of installing.
https://github.com/splunk/splunk-connect-for-kubernetes/issues/571
https://github.com/splunk/splunk-connect-for-kubernetes/issues/565
=> Add unsupported note to YAML deployment method

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/clusterRole.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/clusterRole.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/clusterRoleAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/clusterRole.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/deployment.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
These commits restore the collection of non-aggregated metrics when PodSecurityPolicies are enabled.
The PodSecurityPolicy API was moved from the extensions to the policy group back in 1.10; support for extensions was removed in 1.16.
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
The second commit sets runAsNonRoot to an explicit false to allow the metrics and objects pods/containers to start successfully for a cluster with a default RunAsNonRoot PodSecurityPolicy rule.
=> Fix metrics collection when PodSecurityPolicies are enabled

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
The commit https://github.com/splunk/splunk-connect-for-kubernetes/commit/51b94c2a190ec9f8a3f793f5d4d078f1e776d47b renamed the field 'index' to  'splunk_index'. The change where not done for the non-container log files filter. Logfiles are therefore sendt to the main index.
This PR renames the field to splunk_index so that the logs are sendt to the correct index
=> bugfix for #603 : the text .record.index where not replaced with  .record.splunk_index during the renaming of the field.

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
* fix typo in values.yaml for splunk-kubernetes-logging (closes #583)
* remove unused serviceAccount.usePullSecrets variable for splunk-kubernetes-logging
=> Fix typo in image.pullSecretName variable for splunk-kubernetes-logging

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/deployment.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml
Pod annotations are not available for all deployment with splunk-connect, I added the possibility to set a pod annotations for all daemon set and deployment. This is very usefull if you have for instance istio and you want to disable the istio side-car injection.
=> Add PodAnnotations feature

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
Fixes Issue #633. Tightens the regular expression for the logFormatType=cri  to prevent time field from absorbing arbitrary portions of the log line.
To see this in action simply use this example text:
`2016-02-17T00:04:05.931087621Z stdout F this part of the log entry gets clipped stderr F foobar`
And the broken regex here:
` ^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$`
You'll see that the regular expression will match the last reference to "stdout" or "stderr" causing anything between the extra stdout/stderr to be clipped and not included in the log line.
When changed to the suggested regex:
`^(?<time>[^\s]+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$`
Extra log values are not clipped and the second entry contains the full log property
This regular …
=> Fixes Issue #633. Tightens the regular expression for the logFormatType=cri causing log clipping

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
Add comment for "json" logFormat regex
Add comment for "json" logFormat regex - current regex and that it cannot be modified for logFormatType: json. Long story short, there were some questions related to that parameter and how it works for "json" option.
=> Add comment for "json" logFormat regex

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/service-headless.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceMonitor.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
At the moment Prometheus metrics are set up with the legacy method for target detection.     
This pull request allows to optionally deploy a ServiceMonitor object which can be picked up by an Prometheus operator.
=> implementing ServiceMonitor for usage by the prometheus operator

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/deployment.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
This change Defines priorityClassName to assign a priority class to splunk-kubernetes-objects  pods.
we are planning to implement pod priority to monitoring and logging deployments and daemonsets. the current version does not support that for splunk-kubernetes-objects  deployment.
=> Include priorityClassName for splunk-kubernetes-objects

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/deployment.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml, test/test_setup.yaml
Adding monitor agent for all pods for polling. https://github.com/splunk/splunk-connect-for-kubernetes/issues/609
can be configured to send it to index set in `Values.global.monitoring_agent_index_name` 
Adding liveness probes per request https://github.com/splunk/splunk-connect-for-kubernetes/issues/626
=> enable monitoring agent for all pods and add liveness probes

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
In ruby, `^` points to starting of a line and `$` points to ending of line irrespective of multiline option.
If a multiline log message contains an empty line, ^$ matches the string and the f]grep filter drops the event.
To overcome this issue, use `\A` which points to the start of the string and `\z` which points to the end of the string
=> Updated filter regex which remove empty lines

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
Adds the ability to set a `priorityClassName` on the metrics aggregator pod, so it can be prioritised above (or below) other pods.
All the other pods in this chart have the ability to set this - see #637 and #172. Only the metrics aggregator is missing.
I've added a new `priorityClassNameAgg` value rather than reusing the existing `priorityClassName`, because daemonset pods typically need a higher priority than the deployment pods.
=> Include priorityClassName for the metrics aggregator deployment/pod

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/service-headless.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
This is an adjustment to https://github.com/splunk/splunk-connect-for-kubernetes/pull/288. ClusterIP is needed in some scenarios for metrics ingestion (I need it for use with [signalfx](https://docs.signalfx.com/en/latest/integrations/agent/monitors/prometheus-exporter.html)). This enables you to control whether the service created for metrics is headless or not and allows you to have a service without a ServiceMonitor. Headless defaults to true to preserve existing behavior as default.
=> Add support for a regular ClusterIP service

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
Fixing https://github.com/splunk/splunk-connect-for-kubernetes/issues/601
- HEC token were getting ingested in Splunk logs  
- Added filter to exclude logs having hec token
=> Remove hec token from splunk logs

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
Fixing https://github.com/splunk/splunk-connect-for-kubernetes/issues/621
=> enabled custom filters in metric-aggr

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml
Resolves issue (#652). This change adds additional labels to the metrics aggregator daemon set and deployment to allow for querying pods by the respective types: aggregator and collector. When using tools like [k9s](https://k9scli.io/) it is unable to differentiate the difference between the aggregator (deployment) and collector (daemon set) pods because all of the labels are the same.
=> Add labels to differentiate splunk-kubernetes-metrics deployment and daemon set pods

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
There was no possibilities to send logs from different containers within one pod in k8s cluster to different splunk's indexes. I added the possibility in the change, it is enough to add annotations similar to : 
splunk.com/index.CONTAINER_NAME: index
For example
splunk.com/index.httpbin: index1
splunk.com/index.istio-proxy: index2
- [x ] New feature (non-breaking change which adds functionality)
- [ x] I have read the [CONTRIBUTING](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CONTRIBUTING.md) doc
- [ x] I have read the [CLA](https://github.com/splunk/splunk-connect-for-kubernetes/blob/develop/CLA.md)
- [ x] I have added necessary documentation …
=> Add possibility to send logs from different containers to different indexes from one pod in k8s

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml
Move customFilters to a new CUSTOM label to prevent deadlocks when using the concat plugin.  The example multiline configuration will cause deadlocks when timeouts (flush interval) is hit because the customFilters are in the SPLUNK label and the timeout_label will cause it to loop back around to hit the SPLUNK label again.  You also can't use the CONCAT label because it relabels to SPLUNK.
=> move customFilters to it's own label to prevent deadlocks

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
Changes:
- Add feature which allows skipping logs older than some specific time range
New functionality allows skipping files older than some specific time range. This allows avoiding duplicated logs with path which contain wildcards.
Parameter description in fluentd docs: https://docs.fluentd.org/input/tail#limit_recently_modified
Changes only add new parameter. Without specifying this parameter, nothing changes in chart's behavior.
=> Add "limit_recently_modified" parameter

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/deployment.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
This PR introduces a new variable to allow users to set their own custom labels on their deployments/daemonsets. 
Some organizations might have k8s admission controllers that require certain labels to be set, such as labels designating team/org ownership. This would enable such organizations to set the required labels.
=> Allow custom labels on daemonset/deployment/pods

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
Specify a HEC endpoint to use instead of the default
`services/collector` if needed.
Closes https://github.com/splunk/splunk-connect-for-kubernetes/issues/742
Add `.Values.splunk.hec.endpoint` and `.Values.global.splunk.hec.endpoint` to specify `hec_endpoint` in the configuration. This would allow a custom endpoint to be configured for `fluent-plugin-splunk-hec`. A pull request has been prepared for this feature in the plugin's repository: https://github.com/splunk/fluent-plugin-splunk-hec/pull/222
=> Allow HEC endpoint to be specified

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
Configure DaemonSet .spec.updateStrategy.rollingUpdate params if you want to speed up
rolling out a new version. By default only one pod after another is replaced when
upgrading.
Example: replace 5 pods in parallel
```
splunk-kubernetes-logging:
rollingUpdate:
maxUnavailable: 5
splunk-kubernetes-metrics:
rollingUpdate:
maxUnavailable: 5
```
See https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/
or `kubectl explain daemonset.spec.updateStrategy.rollingUpdate` for
documentation of available keys.
Closes #757
=> Allow RollingUpdate params to be configured

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
Existing implementation assumes that the metrics daemonset and the metrics-agg will requirement the same nodeSelector configuration.
However, this may not always be the case. For example, I want to keep management workloads on a set of management nodes. The metrics-agg deployment will count as a management workload. However, I still want to have the metrics daemonset running on all my nodes to collect metrics. With the current template this is not possible and the `.Values.nodeSelector` is common for both the metrics daemonset and the metrics-agg deployment.
This update implements a separate `aggregatorNodeSelector` value to make it distinct from the orignal `nodeSelector` value.
This fixes: https://github.com/splunk/splunk-connect-for-kubernetes/issues/776
What types of changes does your …
=> separate nodeSelector for metrics-agg

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/examples/openshift4-logging-only.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
On OpenShift by default the directory `/var/log/journal` exists
and journald will use this directory for persistent log storage.
See https://www.freedesktop.org/software/systemd/man/journald.conf.html#Storage=
Ref #779
=> Document persistent journald log path /var/log/journal

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/_helpers.tpl, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/_helpers.tpl, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/_helpers.tpl
Add support for image digest under `image.tag`.
Issue: https://github.com/splunk/splunk-connect-for-kubernetes/issues/793
=> helm-chart: add support for image digest

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml, manifests/splunk-kubernetes-logging/daemonset.yaml, manifests/splunk-kubernetes-metrics/daemonset.yaml, manifests/splunk-kubernetes-metrics/deploymentMetricsAggregator.yaml, manifests/splunk-kubernetes-objects/deployment.yaml
According warnig messages printed by K8s 1.22, the old label
`beta.kubernetes.io/os` is deprecated since 1.14.
Message printed by kubectl:
```
W0714 15:21:21.896079 2914669 warnings.go:70] spec.template.spec.nodeSelector[beta.kubernetes.io/os]: deprecated since v1.14; use "kubernetes.io/os" instead
```
Not sure what type of change this is. :-)
=> Use kubernetes.io/os label for node selector

ci_scripts/deploy_connector.sh, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/_helpers.tpl, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/podSecurityPolicy.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/secret.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/service-headless.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceAccount.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/serviceMonitor.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/_helpers.tpl, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/configMapMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/daemonset.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/podSecurityPolicy.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/podSecurityPolicyAggregator.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/secret.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/templates/serviceAccount.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-metrics/values.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/_helpers.tpl, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/deployment.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/podSecurityPolicy.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/secret.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/templates/serviceAccount.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
Currently, almost all resources being supplied by these charts are defaulting to `.Release.Namespace`. This is generally fine, but it's not configurable, and it doesn't support Gitops because `helm template` does not add `.Release.Namespace` for manifests (https://github.com/helm/helm/issues/3553). The result is that if you try to create the manifests and then apply them without using `helm install`, everything will be put in the `default` namespace
This makes `Namespace` explicit on all relevant resources.
=> Add support for configuring namespaces

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
https://github.com/splunk/fluent-plugin-splunk-hec/pull/250
Support potential new flag for gzip compression from:
https://github.com/splunk/fluent-plugin-splunk-hec/pull/250
Hoping this PR might help with visibility on the upstream change.
=> Support setting gzip_compression flag for log forwarder

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml
support of bufferChunkKeys added and set index as default bufferChunkKey
this helps to prevent an issue of missing events if a pod starts up with an index that the hec declines.
Without bufferChunkKeys all events are mixed within the same chunks and the whole chunk gets thrown away if hec does not accept it.
=> Added support for fluentd bufferChunkKeys in logging-pod (fixes #765)

helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml, helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/values.yaml, helm-chart/splunk-connect-for-kubernetes/values.yaml, manifests/splunk-kubernetes-logging/configMap.yaml
https://docs.fluentd.org/input/tail#in_tail-is-sometimes-stopped-when-monitor-lots-of-files.-how-to-avoid-it
> `in_tail` is sometimes stopped when monitoring lots of files. How to avoid it?
> Try to set `enable_stat_watcher false` in in_tail setting. We got several reports that in_tail is stopped when * is included in path, and the problem is resolved by disabling the inotify events.
=> Make enable_stat_watcher configurable
